### PR TITLE
Updating SVT/BST geometry package

### PR DESCRIPTION
**Pull request by RichmondPhysics**
I am updating the SVT/BST geometry in preparation for publishing the CLAS-NOTE on this package. This includes updating to COATJAVA 4a.0.0 (bst/factory.groovy).

### CODE REVIEW

**Comment by maureeungaro** [comment]
This change assume the existence of an env variable "$myCOATJAVALIBS"  ? But such variable is not defined. Where should it point?

**Comment by RichmondPhysics** [comment]
Hi Mauri,


I was about to write to you about this point. I describe the use of this environment variable in the CLAS-NOTE that I am preparing and I'm not sure what is the best way to include that information. I could add it to the usage message or put a link somewhere to the CLAS-NOTE. Is there a time tomorrow when I could stop by and talk about this?


jerry


-----
Dr. Gerard P. Gilfoyle
Physics Department
University of Richmond, VA 23173  USA
e-mail: ggilfoyl@richmond.edu
phone:  804-289-8255
________________________________

**Comment by maureeungaro** [comment]
Yeah I'll be here. Using env is ok but let's make sure everybody use the same.

**Comment by maureeungaro** [comment]
Closed as with discussion with Jerry.

**Pull request closed without merging**
